#coding=utf-8
import sys
import os
resPath = r"F://Client//XGame//Assets//Lua//System//UI//UIWorldBoss"
# 获取所有文件
def get_files(path, rule=".lua"):
    all = []
    for fpathe,dirs,fs in os.walk(path):   # os.walk是获取所有的目录
        for f in fs:
            filename = os.path.join(fpathe,f)
            if filename.endswith(rule):  # 判断是否是"xxx"结尾
                all.append(filename)
    return all

def replace_component(file_path,old_str,new_str):
    try:
        f = open(file_path, 'r+')
        all_lines = f.readlines()
        f.seek(0)
        f.truncate()
        for line in all_lines:
            line = line.replace(old_str, new_str)
            f.write(line)
        f.close()
    except Exception, e:
        print e
def  get_typeof(file):
    
    pass

if __name__ == '__main__':
    files = get_files(resPath)
    # count = 0
    for i in files:
            replace_component(i,r"GetComponent('UnityEngine.Component')",r'GetComponent(typeof(UnityEngine.Component))')
            replace_component(i,r"GetComponent('UnityEngine.Transform')",r'GetComponent(typeof(UnityEngine.Transform))')
            replace_component(i,r"GetComponent('UnityEngine.Material')",r'GetComponent(typeof(UnityEngine.Material))')
            replace_component(i,r"GetComponent('UnityEngine.Light')",r'GetComponent(typeof(UnityEngine.Light))')
            replace_component(i,r"GetComponent('UnityEngine.Rigidbody')",r'GetComponent(typeof(UnityEngine.Rigidbody))')
            replace_component(i,r"GetComponent('UnityEngine.Camera')",r'GetComponent(typeof(UnityEngine.Camera))')
            replace_component(i,r"GetComponent('UnityEngine.AudioSource')",r'GetComponent(typeof(UnityEngine.AudioSource))')
            replace_component(i,r"GetComponent('UnityEngine.Behaviour')",r'GetComponent(typeof(UnityEngine.Behaviour))')
            replace_component(i,r"GetComponent('UnityEngine.MonoBehaviour')",r'GetComponent(typeof(UnityEngine.MonoBehaviour))')
            replace_component(i,r"GetComponent('UnityEngine.GameObject')",r'GetComponent(typeof(UnityEngine.GameObject))')
            replace_component(i,r"GetComponent('UnityEngine.TrackedReference')",r'GetComponent(typeof(UnityEngine.TrackedReference))')
            replace_component(i,r"GetComponent('UnityEngine.Application')",r'GetComponent(typeof(UnityEngine.Application))')
            replace_component(i,r"GetComponent('UnityEngine.Physics')",r'GetComponent(typeof(UnityEngine.Physics))')
            replace_component(i,r"GetComponent('UnityEngine.Collider')",r'GetComponent(typeof(UnityEngine.Collider))')
            replace_component(i,r"GetComponent('UnityEngine.Time')",r'GetComponent(typeof(UnityEngine.Time))')
            replace_component(i,r"GetComponent('UnityEngine.Texture')",r'GetComponent(typeof(UnityEngine.Texture))')
            replace_component(i,r"GetComponent('UnityEngine.Texture2D')",r'GetComponent(typeof(UnityEngine.Texture2D))')
            replace_component(i,r"GetComponent('UnityEngine.Shader')",r'GetComponent(typeof(UnityEngine.Shader))')
            replace_component(i,r"GetComponent('UnityEngine.Renderer')",r'GetComponent(typeof(UnityEngine.Renderer))')
            replace_component(i,r"GetComponent('UnityEngine.WWW')",r'GetComponent(typeof(UnityEngine.WWW))')
            replace_component(i,r"GetComponent('UnityEngine.Screen')",r'GetComponent(typeof(UnityEngine.Screen))')
            replace_component(i,r"GetComponent('UnityEngine.CameraClearFlags')",r'GetComponent(typeof(UnityEngine.CameraClearFlags))')
            replace_component(i,r"GetComponent('UnityEngine.AudioClip')",r'GetComponent(typeof(UnityEngine.AudioClip))')
            replace_component(i,r"GetComponent('UnityEngine.AssetBundle')",r'GetComponent(typeof(UnityEngine.AssetBundle))')
            replace_component(i,r"GetComponent('UnityEngine.ParticleSystem')",r'GetComponent(typeof(UnityEngine.ParticleSystem))')
            replace_component(i,r"GetComponent('UnityEngine.AsyncOperation')",r'GetComponent(typeof(UnityEngine.AsyncOperation))')
            replace_component(i,r"GetComponent('UnityEngine.LightType')",r'GetComponent(typeof(UnityEngine.LightType))')
            replace_component(i,r"GetComponent('UnityEngine.SleepTimeout')",r'GetComponent(typeof(UnityEngine.SleepTimeout))')
            replace_component(i,r"GetComponent('UnityEngine.Experimental.Director.DirectorPlayer')",r'GetComponent(typeof(UnityEngine.Experimental.Director.DirectorPlayer))')
            replace_component(i,r"GetComponent('UnityEngine.Animator')",r'GetComponent(typeof(UnityEngine.Animator))')
            replace_component(i,r"GetComponent('UnityEngine.Input')",r'GetComponent(typeof(UnityEngine.Input))')
            replace_component(i,r"GetComponent('UnityEngine.KeyCode')",r'GetComponent(typeof(UnityEngine.KeyCode))')
            replace_component(i,r"GetComponent('UnityEngine.SkinnedMeshRenderer')",r'GetComponent(typeof(UnityEngine.SkinnedMeshRenderer))')
            replace_component(i,r"GetComponent('UnityEngine.Space')",r'GetComponent(typeof(UnityEngine.Space))')
            replace_component(i,r"GetComponent('UnityEngine.MeshRenderer')",r'GetComponent(typeof(UnityEngine.MeshRenderer))')
            replace_component(i,r"GetComponent('UnityEngine.ParticleEmitter')",r'GetComponent(typeof(UnityEngine.ParticleEmitter))')
            replace_component(i,r"GetComponent('UnityEngine.ParticleRenderer')",r'GetComponent(typeof(UnityEngine.ParticleRenderer))')
            replace_component(i,r"GetComponent('UnityEngine.ParticleAnimator')",r'GetComponent(typeof(UnityEngine.ParticleAnimator))')
            replace_component(i,r"GetComponent('UnityEngine.BoxCollider')",r'GetComponent(typeof(UnityEngine.BoxCollider))')
            replace_component(i,r"GetComponent('UnityEngine.MeshCollider')",r'GetComponent(typeof(UnityEngine.MeshCollider))')
            replace_component(i,r"GetComponent('UnityEngine.SphereCollider')",r'GetComponent(typeof(UnityEngine.SphereCollider))')
            replace_component(i,r"GetComponent('UnityEngine.CharacterController')",r'GetComponent(typeof(UnityEngine.CharacterController))')
            replace_component(i,r"GetComponent('UnityEngine.CapsuleCollider')",r'GetComponent(typeof(UnityEngine.CapsuleCollider))')
            replace_component(i,r"GetComponent('UnityEngine.Animation')",r'GetComponent(typeof(UnityEngine.Animation))')
            replace_component(i,r"GetComponent('UnityEngine.AnimationClip')",r'GetComponent(typeof(UnityEngine.AnimationClip))')
            replace_component(i,r"GetComponent('UnityEngine.AnimationState')",r'GetComponent(typeof(UnityEngine.AnimationState))')
            replace_component(i,r"GetComponent('UnityEngine.AnimationBlendMode')",r'GetComponent(typeof(UnityEngine.AnimationBlendMode))')
            replace_component(i,r"GetComponent('UnityEngine.QueueMode')",r'GetComponent(typeof(UnityEngine.QueueMode))')
            replace_component(i,r"GetComponent('UnityEngine.PlayMode')",r'GetComponent(typeof(UnityEngine.PlayMode))')
            replace_component(i,r"GetComponent('UnityEngine.WrapMode')",r'GetComponent(typeof(UnityEngine.WrapMode))')
            replace_component(i,r"GetComponent('UnityEngine.QualitySettings')",r'GetComponent(typeof(UnityEngine.QualitySettings))')
            replace_component(i,r"GetComponent('UnityEngine.RenderSettings')",r'GetComponent(typeof(UnityEngine.RenderSettings))')
            replace_component(i,r"GetComponent('UnityEngine.BlendWeights')",r'GetComponent(typeof(UnityEngine.BlendWeights))')
            replace_component(i,r"GetComponent('UnityEngine.RenderTexture')",r'GetComponent(typeof(UnityEngine.RenderTexture))')
            replace_component(i,r"GetComponent('UnityEngine.Resources')",r'GetComponent(typeof(UnityEngine.Resources))')
            replace_component(i,r"GetComponent('UnityEngine.RuntimePlatform')",r'GetComponent(typeof(UnityEngine.RuntimePlatform))')
            replace_component(i,r"GetComponent('List<string>')",r'GetComponent(typeof(List<string>))')
            replace_component(i,r"GetComponent('UnityEngine.PlayerPrefs')",r'GetComponent(typeof(UnityEngine.PlayerPrefs))')
            replace_component(i,r"GetComponent('UnityEngine.SystemInfo')",r'GetComponent(typeof(UnityEngine.SystemInfo))')
            replace_component(i,r"GetComponent('UnityEngine.DeviceType')",r'GetComponent(typeof(UnityEngine.DeviceType))')
            replace_component(i,r"GetComponent('DynamicBone')",r'GetComponent(typeof(DynamicBone))')
            replace_component(i,r"GetComponent('UnityEngine.LightShadows')",r'GetComponent(typeof(UnityEngine.LightShadows))')
            replace_component(i,r"GetComponent('UVMoveLRUDScript')",r'GetComponent(typeof(UVMoveLRUDScript))')
            replace_component(i,r"GetComponent('UIBase')",r'GetComponent(typeof(UIBase))')
            replace_component(i,r"GetComponent('SubUIBase')",r'GetComponent(typeof(SubUIBase))')
            replace_component(i,r"GetComponent('AutoClose')",r'GetComponent(typeof(AutoClose))')
            replace_component(i,r"GetComponent('LuaHelper')",r'GetComponent(typeof(LuaHelper))')
            replace_component(i,r"GetComponent('UIManager')",r'GetComponent(typeof(UIManager))')
            replace_component(i,r"GetComponent('ClickObjectTools')",r'GetComponent(typeof(ClickObjectTools))')
            replace_component(i,r"GetComponent('ClickObject')",r'GetComponent(typeof(ClickObject))')
            replace_component(i,r"GetComponent('SceneLoader')",r'GetComponent(typeof(SceneLoader))')
            replace_component(i,r"GetComponent('UnityEngine.AnimatorStateInfo')",r'GetComponent(typeof(UnityEngine.AnimatorStateInfo))')
            replace_component(i,r"GetComponent('UnGfx')",r'GetComponent(typeof(UnGfx))')
            replace_component(i,r"GetComponent('UnGfx.hitinfo')",r'GetComponent(typeof(UnGfx.hitinfo))')
            replace_component(i,r"GetComponent('UnityEngine.CollisionFlags')",r'GetComponent(typeof(UnityEngine.CollisionFlags))')
            replace_component(i,r"GetComponent('UIHelper')",r'GetComponent(typeof(UIHelper))')
            replace_component(i,r"GetComponent('StandardAssertMgr')",r'GetComponent(typeof(StandardAssertMgr))')
            replace_component(i,r"GetComponent('ResourceManager')",r'GetComponent(typeof(ResourceManager))')
            replace_component(i,r"GetComponent('ResourceManager.Priority')",r'GetComponent(typeof(ResourceManager.Priority))')
            replace_component(i,r"GetComponent('NetworkManager')",r'GetComponent(typeof(NetworkManager))')
            replace_component(i,r"GetComponent('MsgPacket')",r'GetComponent(typeof(MsgPacket))')
            replace_component(i,r"GetComponent('Seeker')",r'GetComponent(typeof(Seeker))')
            replace_component(i,r"GetComponent('AIFollow')",r'GetComponent(typeof(AIFollow))')
            replace_component(i,r"GetComponent('Pathfinding.Path')",r'GetComponent(typeof(Pathfinding.Path))')
            replace_component(i,r"GetComponent('AIPath')",r'GetComponent(typeof(AIPath))')
            replace_component(i,r"GetComponent('LuaUIEventListener')",r'GetComponent(typeof(LuaUIEventListener))')
            replace_component(i,r"GetComponent('Pathfinding.SimpleSmoothModifier')",r'GetComponent(typeof(Pathfinding.SimpleSmoothModifier))')
            replace_component(i,r"GetComponent('Pathfinding.FunnelModifier')",r'GetComponent(typeof(Pathfinding.FunnelModifier))')
            replace_component(i,r"GetComponent('UIMessageBox')",r'GetComponent(typeof(UIMessageBox))')
            replace_component(i,r"GetComponent('GameManager')",r'GetComponent(typeof(GameManager))')
            replace_component(i,r"GetComponent('LoopTool')",r'GetComponent(typeof(LoopTool))')
            replace_component(i,r"GetComponent('TweenPositionArc')",r'GetComponent(typeof(TweenPositionArc))')
            replace_component(i,r"GetComponent('SimpleRpgCamera')",r'GetComponent(typeof(SimpleRpgCamera))')
            replace_component(i,r"GetComponent('ChatCSharp')",r'GetComponent(typeof(ChatCSharp))')
            replace_component(i,r"GetComponent('FilterHelper')",r'GetComponent(typeof(FilterHelper))')
            replace_component(i,r"GetComponent('YMIMInstance')",r'GetComponent(typeof(YMIMInstance))')
            replace_component(i,r"GetComponent('YMTalkInstance')",r'GetComponent(typeof(YMTalkInstance))')
            replace_component(i,r"GetComponent('YIMEngine.IMAPI')",r'GetComponent(typeof(YIMEngine.IMAPI))')
            replace_component(i,r"GetComponent('SoundManager')",r'GetComponent(typeof(SoundManager))')
            replace_component(i,r"GetComponent('ShakeCamera')",r'GetComponent(typeof(ShakeCamera))')
            replace_component(i,r"GetComponent('GridManager')",r'GetComponent(typeof(GridManager))')
            replace_component(i,r"GetComponent('PopListView')",r'GetComponent(typeof(PopListView))')
            replace_component(i,r"GetComponent('WellFired.USSequencer')",r'GetComponent(typeof(WellFired.USSequencer))')
            replace_component(i,r"GetComponent('RotateUI')",r'GetComponent(typeof(RotateUI))')
            replace_component(i,r"GetComponent('ClipParticle')",r'GetComponent(typeof(ClipParticle))')
            replace_component(i,r"GetComponent('DrawTool')",r'GetComponent(typeof(DrawTool))')
            replace_component(i,r"GetComponent('DrawingPencil')",r'GetComponent(typeof(DrawingPencil))')
            replace_component(i,r"GetComponent('YFSDK.YFSDKManager')",r'GetComponent(typeof(YFSDK.YFSDKManager))')
            replace_component(i,r"GetComponent('YFSDK.UserInfo')",r'GetComponent(typeof(YFSDK.UserInfo))')
            replace_component(i,r"GetComponent('YFSDK.RoleParams')",r'GetComponent(typeof(YFSDK.RoleParams))')
            replace_component(i,r"GetComponent('YFSDK.OrderInfo')",r'GetComponent(typeof(YFSDK.OrderInfo))')
            replace_component(i,r"GetComponent('ChannelImageDate')",r'GetComponent(typeof(ChannelImageDate))')
            replace_component(i,r"GetComponent('QuickSDKManager')",r'GetComponent(typeof(QuickSDKManager))')
            replace_component(i,r"GetComponent('quicksdk.OrderInfo')",r'GetComponent(typeof(quicksdk.OrderInfo))')
            replace_component(i,r"GetComponent('quicksdk.GameRoleInfo')",r'GetComponent(typeof(quicksdk.GameRoleInfo))')
            replace_component(i,r"GetComponent('LuaOperationBase')",r'GetComponent(typeof(LuaOperationBase))')
            replace_component(i,r"GetComponent('UILuaOperation')",r'GetComponent(typeof(UILuaOperation))')
            replace_component(i,r"GetComponent('UIEventListener')",r'GetComponent(typeof(UIEventListener))')
            replace_component(i,r"GetComponent('UIInput')",r'GetComponent(typeof(UIInput))')
            replace_component(i,r"GetComponent('NGUITools')",r'GetComponent(typeof(NGUITools))')
            replace_component(i,r"GetComponent('NGUIText')",r'GetComponent(typeof(NGUIText))')
            replace_component(i,r"GetComponent('NGUIText.Alignment')",r'GetComponent(typeof(NGUIText.Alignment))')
            replace_component(i,r"GetComponent('EventDelegate')",r'GetComponent(typeof(EventDelegate))')
            replace_component(i,r"GetComponent('SpringPanel')",r'GetComponent(typeof(SpringPanel))')
            replace_component(i,r"GetComponent('UIWidget.Pivot')",r'GetComponent(typeof(UIWidget.Pivot))')
            replace_component(i,r"GetComponent('UITextList')",r'GetComponent(typeof(UITextList))')
            replace_component(i,r"GetComponent('UIParticle')",r'GetComponent(typeof(UIParticle))')
            replace_component(i,r"GetComponent('UIButtonColor')",r'GetComponent(typeof(UIButtonColor))')
            replace_component(i,r"GetComponent('UIWidgetContainer')",r'GetComponent(typeof(UIWidgetContainer))')
            replace_component(i,r"GetComponent('UIButton')",r'GetComponent(typeof(UIButton))')
            replace_component(i,r"GetComponent('UILabel')",r'GetComponent(typeof(UILabel))')
            replace_component(i,r"GetComponent('UIRect')",r'GetComponent(typeof(UIRect))')
            replace_component(i,r"GetComponent('UISprite')",r'GetComponent(typeof(UISprite))')
            replace_component(i,r"GetComponent('UIWidget')",r'GetComponent(typeof(UIWidget))')
            replace_component(i,r"GetComponent('UIBasicSprite')",r'GetComponent(typeof(UIBasicSprite))')
            replace_component(i,r"GetComponent('UIBasicSprite.Flip')",r'GetComponent(typeof(UIBasicSprite.Flip))')
            replace_component(i,r"GetComponent('UIPanel')",r'GetComponent(typeof(UIPanel))')
            replace_component(i,r"GetComponent('UISlider')",r'GetComponent(typeof(UISlider))')
            replace_component(i,r"GetComponent('UIFont')",r'GetComponent(typeof(UIFont))')
            replace_component(i,r"GetComponent('UIProgressBar')",r'GetComponent(typeof(UIProgressBar))')
            replace_component(i,r"GetComponent('UIScrollView')",r'GetComponent(typeof(UIScrollView))')
            replace_component(i,r"GetComponent('TweenPosition')",r'GetComponent(typeof(TweenPosition))')
            replace_component(i,r"GetComponent('TweenScale')",r'GetComponent(typeof(TweenScale))')
            replace_component(i,r"GetComponent('TweenRotation')",r'GetComponent(typeof(TweenRotation))')
            replace_component(i,r"GetComponent('TweenAlpha')",r'GetComponent(typeof(TweenAlpha))')
            replace_component(i,r"GetComponent('TweenTransform')",r'GetComponent(typeof(TweenTransform))')
            replace_component(i,r"GetComponent('UITweener')",r'GetComponent(typeof(UITweener))')
            replace_component(i,r"GetComponent('UITweener.Style')",r'GetComponent(typeof(UITweener.Style))')
            replace_component(i,r"GetComponent('UITweener.Method')",r'GetComponent(typeof(UITweener.Method))')
            replace_component(i,r"GetComponent('UIPlayTween')",r'GetComponent(typeof(UIPlayTween))')
            replace_component(i,r"GetComponent('UICamera')",r'GetComponent(typeof(UICamera))')
            replace_component(i,r"GetComponent('UICamera.MouseOrTouch')",r'GetComponent(typeof(UICamera.MouseOrTouch))')
            replace_component(i,r"GetComponent('UIToggle')",r'GetComponent(typeof(UIToggle))')
            replace_component(i,r"GetComponent('UIGrid')",r'GetComponent(typeof(UIGrid))')
            replace_component(i,r"GetComponent('UITable')",r'GetComponent(typeof(UITable))')
            replace_component(i,r"GetComponent('UIPopupList')",r'GetComponent(typeof(UIPopupList))')
            replace_component(i,r"GetComponent('UIDragScrollView')",r'GetComponent(typeof(UIDragScrollView))')
            replace_component(i,r"GetComponent('SpinWithMouse')",r'GetComponent(typeof(SpinWithMouse))')
            replace_component(i,r"GetComponent('SetRenderQueue')",r'GetComponent(typeof(SetRenderQueue))')
            replace_component(i,r"GetComponent('UIRoot')",r'GetComponent(typeof(UIRoot))')
            replace_component(i,r"GetComponent('UICenterOnChild')",r'GetComponent(typeof(UICenterOnChild))')
            replace_component(i,r"GetComponent('UIWrapContent')",r'GetComponent(typeof(UIWrapContent))')
            replace_component(i,r"GetComponent('EasyMgr')",r'GetComponent(typeof(EasyMgr))')
            replace_component(i,r"GetComponent('ARSimpleRpgCamera')",r'GetComponent(typeof(ARSimpleRpgCamera))')
            replace_component(i,r"GetComponent('DragPartner')",r'GetComponent(typeof(DragPartner))')
            replace_component(i,r"GetComponent('UILabel.Effect')",r'GetComponent(typeof(UILabel.Effect))')
            replace_component(i,r"GetComponent('CollectTool')",r'GetComponent(typeof(CollectTool))')
            replace_component(i,r"GetComponent('TweenFill')",r'GetComponent(typeof(TweenFill))')
            replace_component(i,r"GetComponent('AppConst')",r'GetComponent(typeof(AppConst))')
            replace_component(i,r"GetComponent('UILabel.Overflow')",r'GetComponent(typeof(UILabel.Overflow))')
            replace_component(i,r"GetComponent('UIScrollBar')",r'GetComponent(typeof(UIScrollBar))')
            replace_component(i,r"GetComponent('DisplayCamera')",r'GetComponent(typeof(DisplayCamera))')
            replace_component(i,r"GetComponent('UnityEngine.SceneManagement.SceneManager')",r'GetComponent(typeof(UnityEngine.SceneManagement.SceneManager))')
            replace_component(i,r"GetComponent('SdkManager')",r'GetComponent(typeof(SdkManager))')
            replace_component(i,r"GetComponent('UIAnchor')",r'GetComponent(typeof(UIAnchor))')
            replace_component(i,r"GetComponent('ClipboradTools')",r'GetComponent(typeof(ClipboradTools))')
            replace_component(i,r"GetComponent('LocalNotification')",r'GetComponent(typeof(LocalNotification))')
            replace_component(i,r"GetComponent('UnityEngine.MeshRenderer')",r'GetComponent(typeof(UnityEngine.MeshRenderer))')
            replace_component(i,r"GetComponent('UnityEngine.ParticleEmitter')",r'GetComponent(typeof(UnityEngine.ParticleEmitter))')
            replace_component(i,r"GetComponent('UnityEngine.ParticleRenderer')",r'GetComponent(typeof(UnityEngine.ParticleRenderer))')
            replace_component(i,r"GetComponent('UnityEngine.ParticleAnimator')",r'GetComponent(typeof(UnityEngine.ParticleAnimator))')
            replace_component(i,r"GetComponent('UnityEngine.BoxCollider')",r'GetComponent(typeof(UnityEngine.BoxCollider))')
            replace_component(i,r"GetComponent('UnityEngine.MeshCollider')",r'GetComponent(typeof(UnityEngine.MeshCollider))')
            replace_component(i,r"GetComponent('UnityEngine.SphereCollider')",r'GetComponent(typeof(UnityEngine.SphereCollider))')
            replace_component(i,r"GetComponent('UnityEngine.CharacterController')",r'GetComponent(typeof(UnityEngine.CharacterController))')
            replace_component(i,r"GetComponent('UnityEngine.CapsuleCollider')",r'GetComponent(typeof(UnityEngine.CapsuleCollider))')
            replace_component(i,r"GetComponent('UnityEngine.Animation')",r'GetComponent(typeof(UnityEngine.Animation))')
            replace_component(i,r"GetComponent('UnityEngine.AnimationClip')",r'GetComponent(typeof(UnityEngine.AnimationClip))')
            replace_component(i,r"GetComponent('UnityEngine.AnimationState')",r'GetComponent(typeof(UnityEngine.AnimationState))')
            replace_component(i,r"GetComponent('UnityEngine.BlendWeights')",r'GetComponent(typeof(UnityEngine.BlendWeights))')
            replace_component(i,r"GetComponent('UnityEngine.RenderTexture')",r'GetComponent(typeof(UnityEngine.RenderTexture))')
            replace_component(i,r"GetComponent('UnityEngine.Rigidbody')",r'GetComponent(typeof(UnityEngine.Rigidbody))')
            replace_component(i,r"GetComponent('')",r'GetComponent(typeof())')

            
            # replace_component(i,r'"Component"',"typeof(Component)")
            # replace_component(i,r'"Transform"',"typeof(Transform)")
            # replace_component(i,r'"Material"',"typeof(Material)")
            # replace_component(i,r'"Light"',"typeof(Light)")
            # replace_component(i,r'"Rigidbody"',"typeof(Rigidbody)")
            # replace_component(i,r'"Camera"',"typeof(Camera)")
            # replace_component(i,r'"AudioSource"',"typeof(AudioSource)")
            # replace_component(i,r'"Behaviour"',"typeof(Behaviour)")
            # replace_component(i,r'"MonoBehaviour"',"typeof(MonoBehaviour)")
            # replace_component(i,r'"GameObject"',"typeof(GameObject)")
            # replace_component(i,r'"TrackedReference"',"typeof(TrackedReference)")
            # replace_component(i,r'"Application"',"typeof(Application)")
            # replace_component(i,r'"Physics"',"typeof(Physics)")
            # replace_component(i,r'"Collider"',"typeof(Collider)")
            # replace_component(i,r'"Time"',"typeof(Time)")
            # replace_component(i,r'"Texture"',"typeof(Texture)")
            # replace_component(i,r'"Texture2D"',"typeof(Texture2D)")
            # replace_component(i,r'"Shader"',"typeof(Shader)")
            # replace_component(i,r'"Renderer"',"typeof(Renderer)")
            # replace_component(i,r'"WWW"',"typeof(WWW)")
            # replace_component(i,r'"Screen"',"typeof(Screen)")
            # replace_component(i,r'"CameraClearFlags"',"typeof(CameraClearFlags)")
            # replace_component(i,r'"AudioClip"',"typeof(AudioClip)")
            # replace_component(i,r'"AssetBundle"',"typeof(AssetBundle)")
            # replace_component(i,r'"ParticleSystem"',"typeof(ParticleSystem)")
            # replace_component(i,r'"AsyncOperation"',"typeof(AsyncOperation)")
            # replace_component(i,r'"LightType"',"typeof(LightType)")
            # replace_component(i,r'"SleepTimeout"',"typeof(SleepTimeout)")
            # replace_component(i,r'"UnityEngine.Experimental.Director.DirectorPlayer"',"typeof(UnityEngine.Experimental.Director.DirectorPlayer)")
            # replace_component(i,r'"Animator"',"typeof(Animator)")
            # replace_component(i,r'"Input"',"typeof(Input)")
            # replace_component(i,r'"KeyCode"',"typeof(KeyCode)")
            # replace_component(i,r'"SkinnedMeshRenderer"',"typeof(SkinnedMeshRenderer)")
            # replace_component(i,r'"Space"',"typeof(Space)")
            # replace_component(i,r'"MeshRenderer"',"typeof(MeshRenderer)")
            # replace_component(i,r'"ParticleEmitter"',"typeof(ParticleEmitter)")
            # replace_component(i,r'"ParticleRenderer"',"typeof(ParticleRenderer)")
            # replace_component(i,r'"ParticleAnimator"',"typeof(ParticleAnimator)")
            # replace_component(i,r'"BoxCollider"',"typeof(BoxCollider)")
            # replace_component(i,r'"MeshCollider"',"typeof(MeshCollider)")
            # replace_component(i,r'"SphereCollider"',"typeof(SphereCollider)")
            # replace_component(i,r'"CharacterController"',"typeof(CharacterController)")
            # replace_component(i,r'"CapsuleCollider"',"typeof(CapsuleCollider)")
            # replace_component(i,r'"Animation"',"typeof(Animation)")
            # replace_component(i,r'"AnimationClip"',"typeof(AnimationClip)")
            # replace_component(i,r'"AnimationState"',"typeof(AnimationState)")
            # replace_component(i,r'"AnimationBlendMode"',"typeof(AnimationBlendMode)")
            # replace_component(i,r'"QueueMode"',"typeof(QueueMode)")
            # replace_component(i,r'"PlayMode"',"typeof(PlayMode)")
            # replace_component(i,r'"WrapMode"',"typeof(WrapMode)")
            # replace_component(i,r'"QualitySettings"',"typeof(QualitySettings)")
            # replace_component(i,r'"RenderSettings"',"typeof(RenderSettings)")
            # replace_component(i,r'"BlendWeights"',"typeof(BlendWeights)")
            # replace_component(i,r'"RenderTexture"',"typeof(RenderTexture)")
            # replace_component(i,r'"Resources"',"typeof(Resources)")
            # replace_component(i,r'"RuntimePlatform"',"typeof(RuntimePlatform)")
            # replace_component(i,r'"List<string>"',"typeof(List<string>)")
            # replace_component(i,r'"PlayerPrefs"',"typeof(PlayerPrefs)")
            # replace_component(i,r'"SystemInfo"',"typeof(SystemInfo)")
            # replace_component(i,r'"DeviceType"',"typeof(DeviceType)")
            # replace_component(i,r'"DynamicBone"',"typeof(DynamicBone)")
            # replace_component(i,r'"LightShadows"',"typeof(LightShadows)")
            # replace_component(i,r'"UVMoveLRUDScript"',"typeof(UVMoveLRUDScript)")


            # replace_component(i,r'"UIBase"',"typeof(UIBase)")
            # replace_component(i,r'"SubUIBase"',"typeof(SubUIBase)")
            # replace_component(i,r'"AutoClose"',"typeof(AutoClose)")
            # replace_component(i,r'"LuaHelper"',"typeof(LuaHelper)")
            # replace_component(i,r'"UIManager"',"typeof(UIManager)")
            # replace_component(i,r'"ClickObjectTools"',"typeof(ClickObjectTools)")
            # replace_component(i,r'"ClickObject"',"typeof(ClickObject)")
            # replace_component(i,r'"SceneLoader"',"typeof(SceneLoader)")
            # replace_component(i,r'"AnimatorStateInfo"',"typeof(AnimatorStateInfo)")
            # replace_component(i,r'"UnGfx"',"typeof(UnGfx)")
            # replace_component(i,r'"UnGfx.hitinfo"',"typeof(UnGfx.hitinfo)")
            # replace_component(i,r'"CollisionFlags"',"typeof(CollisionFlags)")
            # replace_component(i,r'"UIHelper"',"typeof(UIHelper)")
            # replace_component(i,r'"StandardAssertMgr"',"typeof(StandardAssertMgr)")
            # replace_component(i,r'"ResourceManager"',"typeof(ResourceManager)")
            # replace_component(i,r'"ResourceManager.Priority"',"typeof(ResourceManager.Priority)")
            # replace_component(i,r'"NetworkManager"',"typeof(NetworkManager)")
            # replace_component(i,r'"MsgPacket"',"typeof(MsgPacket)")
            # replace_component(i,r'"Seeker"',"typeof(Seeker)")
            # replace_component(i,r'"AIFollow"',"typeof(AIFollow)")
            # replace_component(i,r'"Pathfinding.Path"',"typeof(Pathfinding.Path)")
            # replace_component(i,r'"AIPath"',"typeof(AIPath)")
            # replace_component(i,r'"LuaUIEventListener"',"typeof(LuaUIEventListener)")
            # replace_component(i,r'"Pathfinding.SimpleSmoothModifier"',"typeof(Pathfinding.SimpleSmoothModifier)")
            # replace_component(i,r'"Pathfinding.FunnelModifier"',"typeof(Pathfinding.FunnelModifier)")
            # replace_component(i,r'"UIMessageBox"',"typeof(UIMessageBox)")
            # replace_component(i,r'"GameManager"',"typeof(GameManager)")
            # replace_component(i,r'"LoopTool"',"typeof(LoopTool)")
            # replace_component(i,r'"TweenPositionArc"',"typeof(TweenPositionArc)")
            # replace_component(i,r'"SimpleRpgCamera"',"typeof(SimpleRpgCamera)")
            # replace_component(i,r'"ChatCSharp"',"typeof(ChatCSharp)")
            # replace_component(i,r'"FilterHelper"',"typeof(FilterHelper)")
            # replace_component(i,r'"YMIMInstance"',"typeof(YMIMInstance)")
            # replace_component(i,r'"YMTalkInstance"',"typeof(YMTalkInstance)")
            # replace_component(i,r'"IMAPI"',"typeof(IMAPI)")
            # replace_component(i,r'"SoundManager"',"typeof(SoundManager)")
            # replace_component(i,r'"ShakeCamera"',"typeof(ShakeCamera)")
            # replace_component(i,r'"GridManager"',"typeof(GridManager)")
            # replace_component(i,r'"PopListView"',"typeof(PopListView)")
            # replace_component(i,r'"WellFired.USSequencer"',"typeof(WellFired.USSequencer)")
            # replace_component(i,r'"RotateUI"',"typeof(RotateUI)")
            # replace_component(i,r'"ClipParticle"',"typeof(ClipParticle)")
            # replace_component(i,r'"DrawTool"',"typeof(DrawTool)")
            # replace_component(i,r'"DrawingPencil"',"typeof(DrawingPencil)")
            # replace_component(i,r'"YFSDKManager"',"typeof(YFSDKManager)")
            # replace_component(i,r'"YFSDK.UserInfo"',"typeof(YFSDK.UserInfo)")
            # replace_component(i,r'"YFSDK.RoleParams"',"typeof(YFSDK.RoleParams)")
            # replace_component(i,r'"YFSDK.OrderInfo"',"typeof(YFSDK.OrderInfo)")
            # replace_component(i,r'"ChannelImageDate"',"typeof(ChannelImageDate)")
            # replace_component(i,r'"QuickSDKManager"',"typeof(QuickSDKManager)")
            # replace_component(i,r'"quicksdk.OrderInfo"',"typeof(quicksdk.OrderInfo)")
            # replace_component(i,r'"quicksdk.GameRoleInfo"',"typeof(quicksdk.GameRoleInfo)")
            # replace_component(i,r'"LuaOperationBase"',"typeof(LuaOperationBase)")
            # replace_component(i,r'"UILuaOperation"',"typeof(UILuaOperation)")
            # replace_component(i,r'"UIEventListener"',"typeof(UIEventListener)")
            # replace_component(i,r'"UIInput"',"typeof(UIInput)")
            # replace_component(i,r'"NGUITools"',"typeof(NGUITools)")
            # replace_component(i,r'"NGUIText"',"typeof(NGUIText)")
            # replace_component(i,r'"NGUIText.Alignment"',"typeof(NGUIText.Alignment)")
            # replace_component(i,r'"EventDelegate"',"typeof(EventDelegate)")
            # replace_component(i,r'"SpringPanel"',"typeof(SpringPanel)")
            # replace_component(i,r'"UIWidget.Pivot"',"typeof(UIWidget.Pivot)")
            # replace_component(i,r'"UITextList"',"typeof(UITextList)")
            # replace_component(i,r'"UIParticle"',"typeof(UIParticle)")
            # replace_component(i,r'"UIButtonColor"',"typeof(UIButtonColor)")
            # replace_component(i,r'"UIWidgetContainer"',"typeof(UIWidgetContainer)")
            # replace_component(i,r'"UIButton"',"typeof(UIButton)")
            # replace_component(i,r'"UILabel"',"typeof(UILabel)")
            # replace_component(i,r'"UIRect"',"typeof(UIRect)")
            # replace_component(i,r'"UISprite"',"typeof(UISprite)")
            # replace_component(i,r'"UIWidget"',"typeof(UIWidget)")
            # replace_component(i,r'"UIBasicSprite"',"typeof(UIBasicSprite)")
            # replace_component(i,r'"UIBasicSprite.Flip"',"typeof(UIBasicSprite.Flip)")
            # replace_component(i,r'"UIPanel"',"typeof(UIPanel)")
            # replace_component(i,r'"UISlider"',"typeof(UISlider)")
            # replace_component(i,r'"UIFont"',"typeof(UIFont)")
            # replace_component(i,r'"UIProgressBar"',"typeof(UIProgressBar)")
            # replace_component(i,r'"UIScrollView"',"typeof(UIScrollView)")
            # replace_component(i,r'"TweenPosition"',"typeof(TweenPosition)")
            # replace_component(i,r'"TweenScale"',"typeof(TweenScale)")
            # replace_component(i,r'"TweenRotation"',"typeof(TweenRotation)")
            # replace_component(i,r'"TweenAlpha"',"typeof(TweenAlpha)")
            # replace_component(i,r'"TweenTransform"',"typeof(TweenTransform)")
            # replace_component(i,r'"UITweener"',"typeof(UITweener)")
            # replace_component(i,r'"UITweener.Style"',"typeof(UITweener.Style)")
            # replace_component(i,r'"UITweener.Method"',"typeof(UITweener.Method)")
            # replace_component(i,r'"UIPlayTween"',"typeof(UIPlayTween)")
            # replace_component(i,r'"UICamera"',"typeof(UICamera)")
            # replace_component(i,r'"UICamera.MouseOrTouch"',"typeof(UICamera.MouseOrTouch)")
            # replace_component(i,r'"UIToggle"',"typeof(UIToggle)")
            # replace_component(i,r'"UIGrid"',"typeof(UIGrid)")
            # replace_component(i,r'"UITable"',"typeof(UITable)")
            # replace_component(i,r'"UIPopupList"',"typeof(UIPopupList)")
            # replace_component(i,r'"UIDragScrollView"',"typeof(UIDragScrollView)")
            # replace_component(i,r'"SpinWithMouse"',"typeof(SpinWithMouse)")
            # replace_component(i,r'"SetRenderQueue"',"typeof(SetRenderQueue)")
            # replace_component(i,r'"UIRoot"',"typeof(UIRoot)")
            # replace_component(i,r'"UICenterOnChild"',"typeof(UICenterOnChild)")
            # replace_component(i,r'"UIWrapContent"',"typeof(UIWrapContent)")
            # replace_component(i,r'"EasyMgr"',"typeof(EasyMgr)")
            # replace_component(i,r'"ARSimpleRpgCamera"',"typeof(ARSimpleRpgCamera)")
            # replace_component(i,r'"DragPartner"',"typeof(DragPartner)")
            # replace_component(i,r'"UILabel.Effect"',"typeof(UILabel.Effect)")
            # replace_component(i,r'"CollectTool"',"typeof(CollectTool)")
            # replace_component(i,r'"TweenFill"',"typeof(TweenFill)")
            # replace_component(i,r'"AppConst"',"typeof(AppConst)")
            # replace_component(i,r'"UILabel.Overflow"',"typeof(UILabel.Overflow)")
            # replace_component(i,r'"UIScrollBar"',"typeof(UIScrollBar)")
            # replace_component(i,r'"DisplayCamera"',"typeof(DisplayCamera)")
            # replace_component(i,r'"SceneManager"',"typeof(SceneManager)")
            # replace_component(i,r'"SdkManager"',"typeof(SdkManager)")
            # replace_component(i,r'"UIAnchor"',"typeof(UIAnchor)")
            # replace_component(i,r'"ClipboradTools"',"typeof(ClipboradTools)")
            # replace_component(i,r'"LocalNotification"',"typeof(LocalNotification)")
            # replace_component(i,r'"MeshRenderer"',"typeof(MeshRenderer)")
            # replace_component(i,r'"ParticleEmitter"',"typeof(ParticleEmitter)")
            # replace_component(i,r'"ParticleRenderer"',"typeof(ParticleRenderer)")
            # replace_component(i,r'"ParticleAnimator"',"typeof(ParticleAnimator)")
            # replace_component(i,r'"BoxCollider"',"typeof(BoxCollider)")
            # replace_component(i,r'"MeshCollider"',"typeof(MeshCollider)")
            # replace_component(i,r'"SphereCollider"',"typeof(SphereCollider)")
            # replace_component(i,r'"CharacterController"',"typeof(CharacterController)")
            # replace_component(i,r'"CapsuleCollider"',"typeof(CapsuleCollider)")
            # replace_component(i,r'"Animation"',"typeof(Animation)")
            # replace_component(i,r'"AnimationClip"',"typeof(AnimationClip)")
            # replace_component(i,r'"AnimationState"',"typeof(AnimationState)")
            # replace_component(i,r'"BlendWeights"',"typeof(BlendWeights)")
            # replace_component(i,r'"RenderTexture"',"typeof(RenderTexture)")
            # replace_component(i,r'"Rigidbody"',"typeof(Rigidbody)")
            print(i)

    #     replace_component(i,r'"UILabel"',r"typeof(UILabel)")
    #     replace_component(i,r'"UISprite"',r"typeof(UISprite)")
    #     replace_component(i,r'"UIScrollView"',r"typeof(UIScrollView)")
    #     replace_component(i,r'"UIGrid"',r"typeof(UIGrid)")
        
    #     replace_component(i,r'"UIPanel"',r"typeof(UIPanel)")
    #     replace_component(i,r'"BoxCollider"',r"typeof(BoxCollider)")
    #     # replace_component(i,r"typeof(UITexture)",r'"UITexture"')
    #     replace_component(i,r'"UIWidget"',r"typeof(UIWidget)")
    #     replace_component(i,r'"LoopTool"',r"typeof(LoopTool)")
    #     replace_component(i,r'"UIEventListener"',r"typeof(UIEventListener)")

    #     if count > 5:
    #         break
    #         pass
    #     print(i)
    print("執行結束")